### ISSUE TITLE
To Do's zur Finalisierung

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#118]
- [x] G-Drive Ordner für Max freigeben
- [ ] bitte ausfüllen @GisstHubana https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Systemumgebung-und-verwendete-Tools

**Comment by GisstHubana** [comment]
Ich habe unseren G-Drive Ordner aufgeräumt. Das orginale Material von Max befindet sich im Ordner: Original Material
![image](https://user-images.githubusercontent.com/122723302/220480511-1840749d-c19f-4b94-b0f8-64b0609300e6.png)

Ausserdem habe ich Max eine Freigabe als Content-Manager geschickt. Er kann also ab sofort unsere Codes laufen lassen.
![image](https://user-images.githubusercontent.com/122723302/220480405-6747ccd7-551c-4490-83dd-ca2d841526c7.png)

**Comment by sajosa** [comment]
Danke, prima
