### ISSUE TITLE
Anlegen und Pflegen der Wiki Struktur

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#12]
ongoing task
https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Home-Projekt-%22ReHealthCo%22-%7C-DMA-Gruppe-D-WS22-23

**Comment by sajosa** [comment]
habe sidebar eingefügt und schon mal etwas aufgeräumt

**Comment by GisstHubana** [comment]
Super danke :)

**Comment by sajosa** [comment]
Struktur steht

**Comment by sajosa** [comment]
Wichtige Erkenntnisse über die Bearbeitung der Sidebare gewonnen und angepasst

**Comment by sajosa** [comment]
Danke an @JanEricSch für finale Formatierung der Sidebar

**Comment by sajosa** [comment]
@JanEricSch 
Ich platze vor Neid, wenn ich das sehe ;)
![image](https://user-images.githubusercontent.com/122606103/215575733-3a978a57-d5d4-4052-ab9c-cf7e1064b376.png)
