### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2023TeamD#126]
Der Archivierungsteil kann noch ausgebaut werden mit einer extra Seite.
- DMP Manche Links sind Kaput 
![image](https://user-images.githubusercontent.com/32547123/222377443-47ecbc58-29fa-401a-b1c4-7e7a80efc526.png)
![image](https://user-images.githubusercontent.com/32547123/222377533-86468ac8-b55b-4929-95ca-cfae7a5004ce.png)
-DMP Lizenzen unklar (welche Lizenz gilt für die Daten, welche für den Code)

- Analyse Figures sind nicht mit dem code verlinkt 
- Analyse 
![image](https://user-images.githubusercontent.com/32547123/222378023-6d18c9f7-2722-4ff5-b533-82417858f4bd.png)
Konnte ich nicht in eurem code finden.

- Wiki Sidebare manche links existieren nicht
-

**Comment by GisstHubana** [comment]
@sajosa @JanEricSch: nicht gefundene Interaction im [Wiki](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Behandlungskosten-%C3%BCber-das-Alter) gekennzeichnet, Plot zum schnelleren Auffinden im EDA-Code ausgelagert

**Comment by sajosa** [comment]
@Fuenfgeld 
Herzlichen Dank für die Hinweise, werden wir noch bearbeiten und finalisieren

**Comment by GisstHubana** [comment]
@sajosa @JanEricSch alle Codelinks im Analyseteil ergänzt

**Comment by sajosa** [comment]
@Fuenfgeld 
Lieber Max,
Wir haben unsere Arbeiten abgeschlossen.
Video wird gleich in den google drive Ordner hochgeladen.
Wir bitten Dich um den Link auf YouTube, den wir gerne noch am Ende unserer read me Datei einfügen würden.
Beste Grüße
Tati, Jan und Sabine
