### ISSUE TITLE
Finaler Test unseres Workflows

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#23]
1. Task anlegen unter Project
2. Issues zuordnen
3. Code zu Issues zuordnen
4. Branch zu main von issue anlegen
5. Code erstellen
6. Code Dokumentieren !!!!
7. Commit the branches
8. Merge
9. Dokumentiere Merge
10. Review?
11. Comit the review
12. Abschliessende Doku --> WIKI ?
13. Issue schiessen
14. Task als Done markieren in Project

**Comment by sajosa** [comment]
**Vorschlag für Workflow**

![Image](https://user-images.githubusercontent.com/122606103/213898433-b9ab4b80-cb09-41d0-a21c-3b81d877aecd.jpeg)

**Comment by sajosa** [comment]
Liebe Beide, 
@GisstHubana @JanEricSch 

ich würde Euch bitte für Euch noch einen Clone des main Verzeichnisses anzulegen, siehe Zeichnung 
![image](https://user-images.githubusercontent.com/122606103/213934917-acd0c387-c637-4b66-91ea-f375700af140.png)

Dies geht am besten über **Fork** 
![image](https://user-images.githubusercontent.com/122606103/213934777-e66e3732-c809-4c8f-bff9-1ffd37e41b20.png)

bei Erfolg gerne die Links zu Eurer entstandenen Übersicht hier als Kommentar einstellen.



Lieben Dank

**Comment by GisstHubana** [comment]
Danke für die bebilderte Übersicht. Hier meine Copy: [https://github.com/GisstHubana/DMA2023TeamD](url)
