### ISSUE TITLE
Read me und Startseite WIKI befüllen

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#24]
Zum Projektabschluss hier Zusammenfassung einstellen
https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/README.md

und Kopie auf Startseite der WIKI
https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Home-%22Projektname%22-%7C-DMA-Gruppe-D-WS22-23

**Comment by sajosa** [comment]
@JanEricSch 
beides deutlich voran getrieben

**Comment by sajosa** [comment]
@JanEricSch 
Leider wird das Lizenz Ikon in der sidebare der Code Seite nicht mehr angezeigt

**Comment by sajosa** [comment]
fehlt nur noch Link zu YouTube

**Comment by JanEricSch** [comment]
@sajosa 
habe die archivierung in sidebar als letztes gesetzt denke das rundet das projekt/ die sidebar gut ab
