### ISSUE TITLE
Datenmanagementplan befüllen

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#27]
Alles zum Plan

**Comment by JanEricSch** [comment]
Ich stelle für uns drei Tabellen spalten im wiki ein
Euch beide gebe ich zuerst mal als Arzt an könnt ihr ja gerne ändern, wir könnten uns auch mehrere Titel geben
Könnt ihr bitte eure Kontaktdaten ausfüllen?
@sajosa @GisstHubana

**Comment by GisstHubana** [comment]
Danke fürs vorausfüllen. @JanEricSch magst du dort echt deine Adresse deines Arbeitgebers angeben? Das kann ja jeder lesen. Email reicht wahrscheinlich aus.

**Comment by sajosa** [comment]
Lieber @JanEricSch wie ist der Stand? Kann ich schon etwas reviewen?

**Comment by JanEricSch** [comment]
@GisstHubana 
hast du da schon Code für die Qualitätssicherung der Daten geschrieben und wenn ja was?
[Code Qualitätssicherung](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Datenmanagementplan-(basierend-auf-FAIR-Kriterien)#313-ma%C3%9Fnahmen-der-qualit%C3%A4tssicherung) <- könntest auch direkt hier einfügen

**Comment by GisstHubana** [comment]
@JanEricSch was bedeutet Qualitätssicherung? Wir haben ja keinen Einfluss darauf wie "gut" die Daten erhoben wurden, die sind ja schon da. Und wir können nicht prüfen ob ein Wert korrekt erhoben wurde, weil wir nur wissen, dass die Daten synthetisch sind. 
Falls du auf die Reproduzierbarkeit hinaus möchtest, dann habe ich das schon implementiert:
Der gesamt Code zum Colab Book Ende: https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=VWWX5CrQFoqz
Kapitel "Version Check", "Calculate the Checksum of the Data Set" und "Value should be "Value should be <del>-4071035851779074396"<del> 

-638227857625026837 (neuer Wert vom 12.02.23)

ich kann gerne an einem anderen Tag den code einfügen, heute würde ich den fokus auf das coden legen, da max immer ins colab book reinschauen möchte und das sollte aufgeräumt sein

**Comment by JanEricSch** [comment]
[hier](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenmanagementplan#31-datenerhebung-daten-generieren-und-bearbeiten) unter Maßnahmen zur Datenbereinigung ein beispiel aus ner vorgängergruppe

Eigentlich wollte ich aber auch auf die test raus mit denen wir prüfen ob der code funktioniert, wäre ja gut wenn wir das auch kurz protokollieren, oder

**Comment by GisstHubana** [comment]
> [hier](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenmanagementplan#31-datenerhebung-daten-generieren-und-bearbeiten) unter Maßnahmen zur Datenbereinigung ein beispiel aus ner vorgängergruppe
> 
> Eigentlich wollte ich aber auch auf die test raus mit denen wir prüfen ob der code funktioniert, wäre ja gut wenn wir das auch kurz protokollieren, oder

Das können wir eigentlich 1:1 übernehmen. Evtl. sind einzelne Schritte bei uns umgedreht, aber im Grunde haben wir genau das Gleiche gemacht
Und der Code zur Reproduzierbarkeit steht am Ende des Colab-Books, wie schon erwähnt
@JanEricSch hast du Zeit das von der Vorgängergruppe zu kopieren? Oder soll ich das bei Gelgenheit machen? Wie gesagt, ich würde heute (also Montag) den Fokus auf den Code legen

**Comment by JanEricSch** [comment]
@GisstHubana dann schreib ich das gleich um

**Comment by JanEricSch** [comment]
@sajosa @GisstHubana 
abgeschlossen wenn ihr zeit habt könnt ihr in noch ein letztes mal überfliegen

**Comment by GisstHubana** [comment]
@JanEricSch @sajosa 
![image](https://user-images.githubusercontent.com/122723302/224147002-07c8bd5f-85d0-4845-808f-257a00c123e1.png)
ist das ein fehlender Link? Oder soll das einfach weg?

**Comment by JanEricSch** [comment]
@GisstHubana 
habe ich tatsächlich nicht eingefügt

**Comment by GisstHubana** [comment]
erledigt
