### ISSUE TITLE
Verbindung zwischen colab und git herstellen

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#3]
@sajosa , @JanEricSch , @GisstHubana

**Comment by JanEricSch** [comment]
Haben wir den Punkt schon abgehakt?

**Comment by sajosa** [comment]
Mir ist nicht ganz klar, ob Max hier die generelle Verbindung meinte, wir ein gemeinsames Notbook anlegen sollten und verbinden, oder ob wir für jede neue Datei eine neue Colab Datei anlegen.
Bin für Besprechung dankbar am Donnerstag.

**Comment by sajosa** [comment]
ok, läut
Wichtig hier noch anzumerken der workflow bei Abschluss von Arbeiten in einem Colab das in **main-** liegt auf jeden Fall bitte fürs Team freigeben in Colab !!! @JanEricSch @GisstHubana
