### ISSUE TITLE
Löschen der alten Notebooks

### ISSUE THREAD

**Issue by GisstHubana** [Fuenfgeld/DMA2023TeamD#37]
Ich bin dafür alle Notebook die nicht zur Hauptdatei gehören zu löschen. Also:
- COVID19_Kostentabellen (wir haben ja schon die Datenbank mit den wichtigen Infos)
- Rohdatenbank
- Rohdatenbank2.0 (weil ein "." in der Überschrift ist)

neu_hello_world... kann meinetwegen für Tests bleiben. 

Was denkt ihr? @sajosa @JanEricSch

**Comment by GisstHubana** [comment]
Und wir könnten unser Hauptnotebook in unseren Titel umbenennen: ReHealthCo

**Comment by sajosa** [comment]
Ich lege einen Test und trash branch an, dahin können wird die Testdateien verschieben, damit Main sauberer wird.

**Comment by sajosa** [comment]
> Und wir könnten unser Hauptnotebook in unseren Titel umbenennen: ReHealthCo

Das können wir am Ende als Zusammenfassung des gesamten Codes gerne machen. Aktuell denke ich,sollten wir bei einer Datei(Notebook) pro Woche(Aufgabe) bleiben.

**Comment by sajosa** [comment]
> Ich bin dafür alle Notebook die nicht zur Hauptdatei gehören zu löschen. Also:
> 
> - COVID19_Kostentabellen (wir haben ja schon die Datenbank mit den wichtigen Infos)
> 
> - Rohdatenbank
> 
> - Rohdatenbank2.0 (weil ein "." in der Überschrift ist)
> 
> 
> 
> neu_hello_world... kann meinetwegen für Tests bleiben. 
> 
> 
> 
> Was denkt ihr? @sajosa @JanEricSch 

Bitte noch das neue Notebook der Datei rohdatenbank_2 in Colab freigeben @GisstHubana (wie gestern) Danke

**Comment by sajosa** [comment]
> Ich bin dafür alle Notebook die nicht zur Hauptdatei gehören zu löschen. Also:
> 
> * COVID19_Kostentabellen (wir haben ja schon die Datenbank mit den wichtigen Infos)
> * Rohdatenbank
> * Rohdatenbank2.0 (weil ein "." in der Überschrift ist)
> 
> neu_hello_world... kann meinetwegen für Tests bleiben.
> 
> Was denkt ihr? @sajosa @JanEricSch

Ich lege eine Test_AND_Trash branch an, in dem sind alle Dateien zu finden und putze main :) um das Problem erst mal zu klären.

**Comment by sajosa** [comment]
Hausputz erledigt :)
Gehe nochmal schlafen

**Comment by GisstHubana** [comment]
Danke fürs Aufräumen :) @sajosa schaut super aus!
Notebook Rohdatenbank 2_0 ist in Colab für euch freigegeben @JanEricSch 
Das ist eine gute Idee jede woche ein neues colab zu erstellen und am Ende eine gesamt Datei @sajosa 
Dann schließe ich mal das Issue. Danke für eure Unterstützung und Rückmeldung :)
