### ISSUE TITLE
ETL-Prozess Programmierung

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#39]
Vorbereitung für die Datapipline Strecke

maine file:
https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/2_ETLAufgaben.ipynb

file in Forks:
@sajosa : https://github.com/sajosa/DMA2023TeamD/blob/main/2_ETLAufgaben.ipynb

**Comment by GisstHubana** [comment]
#42 vgl. mein letzter Post

**Comment by GisstHubana** [comment]
#42  ETL: Tabellenvereinigung ist abgeschlosen :)

In der Datenbank Rehealthco haben wir nun 3113 Patienten, 7041 Conditions, 1715 Medicamente, 1715 Procedures und 182271 Observations.

Wir sollten uns nun überlegen, was wir aus welcher Tabelle haben wollen @sajosa @JanEricSch

**Comment by sajosa** [comment]
Super, das Sind ja ordentliche Zahlen!

**Comment by JanEricSch** [comment]
@GisstHubana 
Macht es Sinn bei der Transformation in [conditions](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Dimensionstabelle-WH_conditions) 'Start' und 'Stop' schon zusammenzurechnen und als 'Dauer/ Aufenthalt' anzugeben?

**Comment by GisstHubana** [comment]
ETL abgeschlossen :)
(Änderungswünsche lassen sich natürlich noch nachträglich hineincoden)
