### ISSUE TITLE
Projektmanagement 

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#40]
Habe die Vorbereitungen für die nächste Woche (KW 4) getroffen:
1. Arbeits Datei in Colab geöffnet
2. Auf Colab Ebene für Tati und Jan freigegeben
3. Auf guitHub hochgeladen in main
4. Datei mit 2_ETLAufgabe.ipnb benannt https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/2_ETLAufgaben.ipynb
5. Meilenstein für die Woche angelegt https://github.com/Fuenfgeld/DMA2023TeamD/milestone/6
6. Issue für die Codier Aufgabe angelegt #39 https://github.com/Fuenfgeld/DMA2023TeamD/issues/39
7. Issue für Gruppenmeeting der KW 4 angelegt #38 https://github.com/Fuenfgeld/DMA2023TeamD/issues/38
8. Issue Projektmanagment KW 4 angelegt

**Comment by sajosa** [comment]
Hier die Zusammenfassung für die kommende Woche vom 23.01.2023 bis zur Abgabe am 29.01.2023

**Comment by GisstHubana** [comment]
@sajosa Top danke für die Vorbereitung :)
Und danke dass du die Datei Max zum Review geschickt hast :)

ich habe mir mal ein wenig das ETL Notebook angesehen und endlich zum ersten Mal den Merge/Join im alten Notebook geschafft.

Die Anfrage lautet:

test1 = "SELECT * FROM medications INNER JOIN patients ON medications.PATIENT = patients.Id" #<- insert your Select here between the "" signs
cur.execute(test1) #cur = cursor Zeiger der auf Daten zeigt, so können die Daten executed werden
records = cur.fetchall() #fetchall holt alles selektierte
for row in records: #Schleife über jede Zeile des records (aus fetchall)
  print(row)
  
In der Aufgabe für nächste Woche sollen wir Tabellen miteinander verknüpfen. Welche Tabellen wollen wir denn verknüpfen? @sajosa @JanEricSch Einfach einmal alle?? Wäre zu diskutieren im morgigen Gruppentreffen.

**Comment by sajosa** [comment]
@GisstHubana @JanEricSch 
Habe die Vorbereitungen für die nächste Woche  getroffen:

Arbeitsdateien in Colab geöffnet, lag schon auf unserem shared drive (Danke Tati)
Auf Colab Ebene für Tati und Jan freigegeben, war schon erledigt :)
Auf guitHub hochgeladen in main

*Dateien* benannt mit  
3_ https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/3_EDA.ipynb und 
4_ https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/4_Prediction.ipynb 

*dev Branch für die Woche* erstellt: https://github.com/Fuenfgeld/DMA2023TeamD/tree/dev_branch_EDA_Prediction

*Meilenstein* für die Woche 
https://github.com/Fuenfgeld/DMA2023TeamD/milestone/7

*Issue* für die Codier Aufgabe angelegt 
https://github.com/Fuenfgeld/DMA2023TeamD/issues/45
https://github.com/Fuenfgeld/DMA2023TeamD/issues/46

*Gruppenmeeting* KW 5
https://github.com/Fuenfgeld/DMA2023TeamD/issues/47
