### ISSUE TITLE
Kombination der Ursprungsdatentabelle

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#42]
Bitte Vorschlag für den notwendigen Code

**Comment by sajosa** [comment]
Meine Idee wäre die datein im google driv umzubenennen in covir_patients, asthma_patients, msd_patients und sie dann einzulesen und dann mit UNION zu einer Gesamt Tabelle patients zusammen zuführen.
Was haltet Ihr davon? @GisstHubana @JanEricSch 
Das war wahrscheinlich ehe die Idee, die Du schon hattest Tati, oder?

**Comment by GisstHubana** [comment]
Ich hab mich jetzt nochmal an der Kombination der Daten versucht, leider noch frustran. Wir können die Tabellen zwar umbenennen aber ich glaube das ist unnütze Zusatzarbeit und bringt uns nicht weiter. 
2 Tabellen über den Join klappt.
Aber eine leere Tabelle mit Daten aus einer vorhandenen Tabelle zu befüllen... das muss gehen! aber ich bekomms gerade nicht hin. Ich würde da jetzt mal ne Nacht drüber schlafen (falls mich die Patienten lassen ;) ) und mich dann nochmal morgen daran setzen. - Deswegen auch wenn wir die Dateien umbenennen müssen wir trotzdem die Tabellen neu befüllen, und das klappt gerade noch nicht. Letzten Endes ist es egal wie die Dateien heissen und wo sie liegen. 
Falls einer von euch mit programmieren möchte mein ETL-Notebook ist noch in meinem TatisETLBranch (ja der kommt bald weg). Da könnt ihr sehen wie weit ich gekommen bin. 

Gute Nacht und bis morgen

**Comment by GisstHubana** [comment]
#39

**Comment by sajosa** [comment]
> Ich hab mich jetzt nochmal an der Kombination der Daten versucht, leider noch frustran. Wir können die Tabellen zwar umbenennen aber ich glaube das ist unnütze Zusatzarbeit und bringt uns nicht weiter. 
> 2 Tabellen über den Join klappt.
> Aber eine leere Tabelle mit Daten aus einer vorhandenen Tabelle zu befüllen... das muss gehen! aber ich bekomms gerade nicht hin. Ich würde da jetzt mal ne Nacht drüber schlafen (falls mich die Patienten lassen ;) ) und mich dann nochmal morgen daran setzen. - Deswegen auch wenn wir die Dateien umbenennen müssen wir trotzdem die Tabellen neu befüllen, und das klappt gerade noch nicht. Letzten Endes ist es egal wie die Dateien heissen und wo sie liegen. 
> Falls einer von euch mit programmieren möchte mein ETL-Notebook ist noch in meinem TatisETLBranch (ja der kommt bald weg). Da könnt ihr sehen wie weit ich gekommen bin. 
> 
> Gute Nacht und bis morgen

So wie ich den bisherigen code verstehe, wird zunächst die Tabelle für unsere Rohdatenbank erstellt und dann mit Daten befüllt. Wäre es denn nicht möglich den Befehl einfach 3mal hintereinander jedesmal mit einer anderen patientstabelle auszuführen? Sodass alle drive dateien in die selbe Rohdatenbanktabelle eingelesen werden?
Da sie alle unterschiedliche pfade haben und darüber ja eindeutig benannt sind, kann man sich die Umbenennung sparen, stimmt!

**Comment by sajosa** [comment]
Allerdings wäre ich für eine neue spalte, die die Information aus welcher datenbank (covid, asthma, msd) die daten stammen ausgeben kann.

**Comment by Fuenfgeld** [comment]
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py
Schaut euch den code mal an den haben eure Vorgänger entwickelt.

**Comment by GisstHubana** [comment]
So, ich bin mit Wochenprogrammieraufgabe durch :)

Es gibt nun ein Haupt-Jupiter-Notebook ReHealth-Co. Es erstellt die Datenbanken Asthma, Covid sowieMetabolic und fügt in jede Datenbank die Tabellen patients, conditions, medications, procedures und observations ein. Anschließend kopiert es patients, conditions, medications, procedures und observations aus allen drei Datenbanken gemeinsam in die neue Datenbank Rehealthco.

Solltet ihr einen "UNIQUE"-Fehler bekommen, dann versucht ihr nochmal die Patiententabelle mit den einzigartigen Ids einzufügen. Das geht natütlich nicht. Einfach diesen Befehl dann auskommentieren, dass sollte das Skript weiterlaufen.

Dank der einzigartigen Ids kommen auch keine Patienten doppelt vor, und dank der Fremdkeys kommt in KEINER Tabelle ein Patient doppelt vor :)

(Hier stand noch Quatsch, ihr müsst nichts löschen! Startet einfach das Notebook und lasst es durchlaufen :) )

**Comment by GisstHubana** [comment]
Und danke an @Fuenfgeld, ich konnte dank deines Hinweises nun die SQL-Befehle in eine Text-Datei auslagern :)

**Comment by sajosa** [comment]
Lieber Max,

herzlichen Dank für die Hilfestellung.

Beste Grüße
Sabine im Namen von Team D


Maximilian Fünfgeld ***@***.***> schrieb am Mi., 25. Jan.
2023, 12:29:

**Comment by sajosa** [comment]
Super, Danke @GisstHubana

**Comment by GisstHubana** [comment]
auch nochmal mit Pandas bestätigt: es gibt keine doppelten Patienten nach zusammenwürfeln der Ursprungstabellen: https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=qVCSCG4Ciiu4&line=3&uniqifier=1
