### ISSUE TITLE
Dev branch anlegen

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#43]
Für den Workflow, wenn wir einReview von Max einholen wollen, brauchen wir einen merg request into main. D.h. geht nur von anderem branch in den wir alle eventuelle Änderungen einsteuern können.
Also vom Dev branch -->pull or fetch auf die eigene Maschiene. Da bearbeiten. Danach --> Staging aeria (noch lokal) und Commit in dev branch (online repository). 
Wenn alle fertig sind, merg request an Max als Chef entwickler und reviewer für main.

**Comment by sajosa** [comment]
Zum Verstandniss hier gut aufbereitet 😀
https://rachelcarmena.github.io/2018/12/12/how-to-teach-git.html

**Comment by sajosa** [comment]
Dev Branch angelegt @GisstHubana  
https://github.com/Fuenfgeld/DMA2023TeamD/tree/dev_branch_ETL_Prozess

**Comment by sajosa** [comment]
Bitte im Git dektop einen pull Request auslösen
![image](https://user-images.githubusercontent.com/122606103/214384241-04fd2af0-f7a4-4b97-bb85-b4496243e9d8.png)

**Comment by GisstHubana** [comment]
Wow du hast dir echt viel Mühe gegeben !! Danke für die Vorabeit !!

**Comment by GisstHubana** [comment]
Da wir nun einen Dev Branch haben sollten wir unsere eigenen branches löschen

**Comment by GisstHubana** [comment]
alte Branches gelöscht
