### ISSUE TITLE
Exploratory Data Analysis (EDA)

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#45]
Objective: 
Exploratory data analysis is a task performed by data scientists to get familiar with the data. All the initial tasks you do to understand your data well are known as EDA.

There are main components of exploring data:

- [x] Understanding data/Basic Data Exploration
- [x] Cleaning dataset
- [x] Understanding variables
- [x] Analyzing relationships between variables

**Comment by GisstHubana** [comment]
Für einen ersten Dateneindruck bitte in #53 schauen, da sind schon ein paar bunte Bilder drin :)

**Comment by sajosa** [comment]
Liebe Tati, @GisstHubana
könnten wirhier nicht gleich unsere Kombinierte ReHealthCo Datenbank laden?

https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/3_EDA.ipynb#scrollTo=HzmmNYDbcnd7&line=1&uniqifier=1

anstelle des Asthma Warehouses?

**Comment by GisstHubana** [comment]
> Liebe Tati, @GisstHubana könnten wirhier nicht gleich unsere Kombinierte ReHealthCo Datenbank laden?
> 
> https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/3_EDA.ipynb#scrollTo=HzmmNYDbcnd7&line=1&uniqifier=1
> 
> anstelle des Asthma Warehouses?

Wie meinst du das? @sajosa  Die Tabellen zu laden, zu kombinieren und dann auszuwerten ist doch unsere Aufgabe. Natürlich könnten wir gleich die kombinierte Tabelle laden, aber ich glaub dann lassen wir einen Teil der Aufgabenstellung aus.

**Comment by GisstHubana** [comment]
Hier fehlt noch unnütze Diagnosen rauszuwerfen
ich hab schon mal angefangen: [Link zum colab-book](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/main/ReHealthCo.ipynb#scrollTo=qxlj70nJ5bIo&line=1&uniqifier=1)

**Comment by sajosa** [comment]
Sorry, kein Problem, mein Versehen

habe zuerst die Übungsaufgabe gesehen, die nur mit den Asthma Daten
arbeitet und nicht die Arbeit im ReHealthCo file.

:)

Das sind die kleinen Misverständnisse beim asynchronen Arbeiten.

Bis heute Abend
HG
Sabine

GisstHubana ***@***.***> schrieb am So., 5. Feb. 2023, 02:06:

**Comment by GisstHubana** [comment]
aso alles klar :)

**Comment by GisstHubana** [comment]
Alle Issues aus diesem Issue abgearbeitet :)
