### ISSUE TITLE
Gruppenmeetings KW 5 (30.1.2023-05.02.2023)

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#47]
Hier Notizen vom Onlinemeeting und ToDos für die Woche

**Comment by sajosa** [comment]
TO DOs aus OnlineTreffen mit Max 30.01.2023 @JanEricSch @GisstHubana 
- [ ] Code in WIKI verlinken
- [ ] Codierarbeit im Dev branch !!!!
- [ ] bei Merge in main Max als Reviewer anfragen!
- [ ] bei Speicherung des Codes Comitmessage generieren
- [x] Daten und Code sollten getrennt gehalten werden
- [ ] sql Text Datei in WIKI verlinken
- [ ] Test in Code drin lassen
- [ ] Test code ein libary auslagern (Max schickt noch Hilfestellung)
- [ ] Sternschema entwickeln, Faktentabelle und Dimensionstabelle (ETL-Schema)

**Comment by sajosa** [comment]
TO DOs 2 aus OnlineTreffen mit Max 30.01.2023 @JanEricSch @GisstHubana

- [ ] Dokumentation des Datenflusses noch als visuelles Schema
- [ ] methode als classen zu definieren (objekt orientiertes Programmieren) = Style Empfehlung kommt von Max
- [x] konsequente Kommunikation in GitHub !!! 
- [x] 250h Arbeitsaufwand, jeder sollte 21Std. pro Wochen eingeben
- [x] Codespace testen, aber nicht benutzen :)

**Comment by sajosa** [comment]
- [x] reset Befehl in Colab als erstes einfügen, damit erst alles gelöscht wird
- [ ] testen die Datenbank im drive anzusehen, ggf für Screenshot geeignet ;) für Doku
datenbank öffnen mit sql viewer , log in and autorize

- [ ] sickit learn für classisches maschine learnen, workflow für bestes Vorgehen choosing the right estimator

**Comment by GisstHubana** [comment]
01.02. 19 Uhr
Link für Videoanruf: https://meet.google.com/kqu-ogep-rjw
Oder telefonisch: ‪(DE) +49 30 300195191‬ PIN: ‪507 296 550‬#
Weitere Telefonnummern: https://tel.meet/kqu-ogep-rjw?pin=7293876503863

06.02. 19 Uhr
Link für Videoanruf: https://meet.google.com/day-dgma-sme
Oder telefonisch: ‪(DE) +49 40 8081619624‬ PIN: ‪522 905 606‬#
Weitere Telefonnummern: https://tel.meet/day-dgma-sme?pin=4519876453084

**Comment by sajosa** [comment]
Hallo Ihr Lieben,
Was habt Ihr den gestern besprochen?
@GisstHubana @JanEricSch 

Die ersten Diagramme sehen ja schon gut aus 😀

**Comment by JanEricSch** [comment]
Haben vor allem unseren Fortschritt dem andern mitgeteilt.

An dich die Frage @sajosa:
- soll ich das DBM in mermaid umsetzen? Kann dir da auch andere Grafiken erstellen

Das Sterndiagram würde ich als Flowchart machen, gibt da ja auch schon in test mermaid ein Vorbild wie das aussehen würde.
Unsere "Zentrale Faktentabelle" heißt rehealthco.db oder? @GisstHubana

**Comment by sajosa** [comment]
Guten Abend:

>>DBM in mermaid umsetzen
Ja gerne, fand ich super, bin ja auch am Projekt Plan dran, finde ich super mit dem weiter geht es gut!

Hatte mir überlegt,dass es gut wäre, wenn wir den Code für die Mermaid Diagramme als text files im diagrammordner unter code abspeichern und dann in die Wiki verlinken. Probiere ich morgen aus.

**Comment by GisstHubana** [comment]
> Haben vor allem unseren Fortschritt dem andern mitgeteilt.
> 
> An dich die Frage @sajosa:
> 
> * soll ich das DBM in mermaid umsetzen? Kann dir da auch andere Grafiken erstellen
> 
> Das Sterndiagram würde ich als Flowchart machen, gibt da ja auch schon in test mermaid ein Vorbild wie das aussehen würde. Unsere "Zentrale Faktentabelle" heißt rehealthco.db oder? @GisstHubana

genau  rehealthco.db 
hier der Ort: /content/drive/Shareddrives/Projektarbeit DMA Gruppe D/source_dbs/rehealthco.db

**Comment by sajosa** [comment]
Hatte gestern leider große Schwierigkeiten mit der Einbindung des Mermaid Projektplans.....markdown kopiert und in wiki eingefügtaber leider keine Anzeige, habe mich jetzt mit svg beholfen. Auslagerung funkioniert auch nicht :(

**Comment by sajosa** [comment]
Heute mermaid wieder als mardown integriert, leider bin ich mit der Farbe noch nicht glücklich, aber so geht es erst mal
