### ISSUE TITLE
Dokumentation EDA

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#48]
Link zur WIKI Seite
https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Faktentabelle-ReHealthCo

- [ ] Überarbeitung Doku Faktentabelle = rhc_df (@janEricSch , habe dir Tabellenkopf aus colab book einkopiert zum Abgleich)
- [ ]

**Comment by sajosa** [comment]
Liebe Tati, @GisstHubana 
könnten wirhier nicht gleich unsere Kombinierte ReHealthCo Datenbank laden?

https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/3_EDA.ipynb#scrollTo=HzmmNYDbcnd7&line=1&uniqifier=1

anstelle des Asthma Warehouses?

**Comment by GisstHubana** [comment]
EDA Notebook überarbeitet und abgeschlossen @sajosa @JanEricSch

**Comment by sajosa** [comment]
neue Heatmap
