### ISSUE TITLE
Forschungsfrage

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#5]
[https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Fragestellung---Hypothese](https://github.com/users/Fuenfgeld/projects/3/views/url)

**Comment by sajosa** [comment]
1. Entwurf Forschungsfrage:
Erhalten Patient:innen eine bessere Behandlung bei (z.B. Normalisierung der Laborwerte, Vitalzeichen) 
im Verhältnis zur Kostenabdeckung (wieviel der "total Cost" wurde von der Versicherung bezahlt? und / oder Liegezeit)

**Comment by GisstHubana** [comment]
Wie brauchen einen Titel für unsere Fragestellung #5
[https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Fragestellung---Hypothese](url)

**Comment by GisstHubana** [comment]
ReHealthCo

**Comment by sajosa** [comment]
erledigt
