### ISSUE TITLE
Dokumantation ETL-Prozess

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#50]
- [ ] Star Schema entwickeln
- [x] Faktentabelle: anonym_rhcpat_df
- [x] Dimensions Tabelle <del>(Snowmed CT, Loinc?)<del>

rhcpat_df, rhccon_df, rhcmed_df, rhcenc_df

**Comment by GisstHubana** [comment]
[Modell Vorgängergruppe](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung)

**Comment by GisstHubana** [comment]
Wiki ELT überarbeitet @JanEricSch @sajosa

**Comment by JanEricSch** [comment]
abgeschlossen
