### ISSUE TITLE
RHC-Datenbankanfragen als Code schreiben

### ISSUE THREAD

**Issue by GisstHubana** [Fuenfgeld/DMA2023TeamD#53]
Folgende Codes werden benötigt:
- [x] Pat.-Alter 
![image](https://user-images.githubusercontent.com/122723302/215871895-0ea22a6e-fb6b-49ac-bbaf-b1fa460f3583.png)
[colabbook-link](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=-cOnWDYuaAZl&line=11&uniqifier=1)
oder
[direkter code link](https://github.com/Fuenfgeld/DMA2023TeamD/commit/d62f365e7380e857794ecc68bb9f104a27f29b5d#:~:text=%22%23%20%23%20calculate%20age,%5D%2C)
- [x] Wieviele Tote: 113 [colabbook-link](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=INRF6p3jnwdG&line=1&uniqifier=1)
- [x] Healthcare_Expenses covered/uncovered
![image](https://user-images.githubusercontent.com/122723302/216793729-d40ce4f4-06f8-49b3-9377-af990d1bc53f.png)
Es scheint eine Korrelation zwischen nicht abgedeckten Healthcare-costs und Alter zu geben
![image](https://user-images.githubusercontent.com/122723302/216793752-32b35c57-02b0-4077-942b-a96f7902c07f.png)
- [x] Absolute Ausgaben im Verhältnis mit Healthcare_Expenses covered: im Schnitt deckt die Versicherung nur 1% ab!
![image](https://user-images.githubusercontent.com/122723302/216793439-adbff571-a011-43ed-89a9-70155c6d835d.png)
und es scheinen keine Korrelation mit anderen Attributen zu bestehen
![image](https://user-images.githubusercontent.com/122723302/216793516-2c9ab5ad-e419-4e5e-b9a6-b4e21f114761.png)
- [x] Sortieren nach Diagnosen (Hinweis: snomed ct Code noch nicht verwendt)
![image](https://user-images.githubusercontent.com/122723302/215880287-fc08b596-9ef7-4fed-bae4-c41bc63b1105.png)
 [colabbook-link ProfileReport](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=fX1My869Rg_r&line=1&uniqifier=1)
oder
[colabbook-link sortiert nach "description"](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=cz-MCpdIjtV2&line=3&uniqifier=1)
- [x] Stationäre Krankenhaustage (Hinweis: Tabelle suchen!! Diese Tabelle hat eine Spalte "Admission date" und eine Kategorie "wellness" etc.)

**Comment by GisstHubana** [comment]
Und eine Extra-Code-Aufgabe: 
- [x] Test code ein libary auslagern (Max schickt noch Hilfestellung)

**Comment by GisstHubana** [comment]
Es scheint eine Korrelation zwischen Alter und Healthcaresexpenses zu geben [colabbook](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/dev_branch_EDA_Prediction/ReHealthCo.ipynb#scrollTo=GDUTS3q4qyYg&line=5&uniqifier=1)
![image](https://user-images.githubusercontent.com/122723302/215891626-93fcf28a-7218-4f54-9fb2-69c52bcafb70.png)

**Comment by GisstHubana** [comment]
Encounters Auswertung (geupdated): 
![image](https://user-images.githubusercontent.com/122723302/218222672-5d85f7cb-7828-419c-a85a-e05c324b616e.png)

**Comment by GisstHubana** [comment]
Alle Tabellen zusammengeworfen und pandas profile report drüber laufen gelassen:
CAVE: ..._x und ..._y sind doppelt!! müssen bei interesse gemerged werden
![image](https://user-images.githubusercontent.com/122723302/217675754-e919301d-1a30-4b82-81eb-cfbffb199adf.png)

**Comment by GisstHubana** [comment]
- [x] [Quelldaten anonymisieren](https://www.youtube.com/watch?v=SihYp9YuCc8) @GisstHubana

**Comment by sajosa** [comment]
> Encounters Auswertung: 
> ![image](https://user-images.githubusercontent.com/122723302/217671733-d43ae72f-5f63-4ea3-88a4-24a4d3506e00.png)
> 

Prima, aber   Mhh 👀 
wo sind die stationären (inpatient) Patienten?

**Comment by GisstHubana** [comment]
# Ziel-Rhc-Tabellen (Name des Attributs, Typ, Quelle)

- [x] Laufende Nr.

- [x] Age

- [x] Lebend/verstorben

- [x] Gender

- [x] Healthcare expenses

- [x] Healthcare Coverage

- [x] Diagnose 1

- [x] Diagnose 2

- [x] Diagnose 3

- [x] More than 3 ja/nein

- [x] Encounter class ambulatory (int)

- [x] Encounter class inpatient

- [ ] Encounter class emergency

- [x] Encounter urgentcare

**Comment by GisstHubana** [comment]
# Bereinigung

- [x] Ausreißer raus

**Comment by GisstHubana** [comment]
> > Encounters Auswertung:
> > ![image](https://user-images.githubusercontent.com/122723302/218222769-e6d92ada-d9ad-475b-9e10-f039d0202040.png)
> 
> Prima, aber Mhh 👀 wo sind die stationären (inpatient) Patienten?

jetzt da

**Comment by GisstHubana** [comment]
Tabellen folgendermaßen vereinigt und Spalten umbenannt @sajosa @JanEricSch :

Zwischentabelle "rhc_verein1_df"
merge(rhcpat_df, rhccon_df, left_on=["Id", "datenbankart"], right_on=["PATIENT", "datenbankart"])
drop("PATIENT")
rename(columns={"DESCRIPTION": "desc_con", "CODE": "code_con", "START": "start_con", "STOP": "stop_con"}

Zwischentabelle rhc_verein2_df:
merge(rhc_verein1_df, rhcmed_df, left_on=["Id", "datenbankart", "ENCOUNTER"], right_on=["PATIENT", "datenbankart", "ENCOUNTER"])
drop("PATIENT")
rename(columns={"DESCRIPTION": "desc_med", "CODE": "code_med", "START": "start_med", "STOP": "stop_med", "REASONDESCRIPTION": "reasondesc_med", "REASONCODE": "reasoncode_med"})

Zieltabelle rhc_vereinall_df (Ausgabe als /content/drive/Shareddrives/Projektarbeit DMA Gruppe D/out.csv)
merge(rhc_verein2_df, rhcenc_df, left_on=["Id", "datenbankart", "PAYER", "PAYER_COVERAGE"], right_on=["PATIENT", "datenbankart", "PAYER", "PAYER_COVERAGE"])
drop("PATIENT")
rename(columns={"DESCRIPTION": "desc_enc", "CODE": "code_enc", "START": "start_enc", "STOP": "stop_enc", "REASONDESCRIPTION": "reasondesc_enc", "REASONCODE": "reasoncode_enc"})

**Comment by GisstHubana** [comment]
Age - Lifetimecost: kein Zusammenhang, da Ergebnis ca 0,48 (also ziemlich genau bei 0,5, also zufällig)

**Comment by GisstHubana** [comment]
@sajosa 
out.csv mit age nun in github:
https://github.com/Fuenfgeld/DMA2023TeamD/tree/main/source_dbs

@sajosa @JanEricSch wir können nicht gleichzeitig auf github und in gdrive arbeiten, da beide über /content mounten und das zu einem Konfilkt führt. Da Max die Referenz zu Github so wichtig war, bin ich für github, der code ist akutell auch für github geschrieben. Ist das für euch in Ordnung?

**Comment by GisstHubana** [comment]
@sajosa @JanEricSch 
Issue abgeschlossen :) alles was besprochen war findet ihr im ETL bzw. EDA Notebook
