### ISSUE TITLE
Data Warehouse (Sternmodell ...)

### ISSUE THREAD

**Issue by JanEricSch** [Fuenfgeld/DMA2023TeamD#54]
Versuch das mit mermaid zu basteln

**Comment by sajosa** [comment]
Bin schon gespannt :)
Sorry musste die Meilensteinzuordnung ändern

**Comment by JanEricSch** [comment]
hey, schaut mal in wiki [Tetst mermaid](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Test-mermaid) rein, hab mal verschiedene diagramme erstellt
könnte auch unser er-modell schnell in mermaid/ markdown übertragen

wenn ihr wünsche habt einfach hier im issue äußern und ich versuch es umzusetzen

@sajosa @GisstHubana

**Comment by JanEricSch** [comment]
Für das Sternmodel würde ich ein Flowchart vorschlagen, habe leider nichts besseres gefunden
@sajosa @GisstHubana 

Mindmaps lassen sich scheinbar noch nicht in github -> markdown übertragen? 
Die Fehlermeldung: "No diagram type detected for text: mindmap"

Danke für die Hilfe
@Fuenfgeld

**Comment by Fuenfgeld** [comment]
https://mermaid.js.org/syntax/flowchart.html?id=flowcharts-basic-syntax Wie wäre es mit einem flowchart

**Comment by Fuenfgeld** [comment]
Es gibt auch Browser Editoren. Erstellt das Diagramm da und kopiert den Code rüber https://mermaid.live/edit#pako:eNpVj81qw0AMhF9F6NRC_AI-BGK7zSXQQHLz5iBsObuk-8Naphjb7551fEl1EjPfiNGEjW8Zc7xHChqulXKQ5lCXOppeLPU3yLL9fGQB6x2PMxQfRw-99iEYd__c-GKFoJxOK8Yg2rjHslnlK__jeIaqPlEQH27vzvXPz_BVm7NO5_87OnJKfdcd5R1lDUUoKb4Q3KHlaMm0qfq0KgpFs2WFeVpb7mj4FYXKLQmlQfxldA3mEgfe4RBaEq4MpaftJi5PNtJU8w

**Comment by JanEricSch** [comment]
Ja ein Flowchart wäre die Alternative.

Habe nur den Eindruck das "mindmap" noch nicht in github wiki implementiert worden ist. Es wirft mir auf jeden Fall immer die selbe Fehlermeldung aus, auch wenn ich das Diagramm im Browser oder Visual Studio Code erstelle und den Code dann in github übertrage.

@Fuenfgeld

**Comment by JanEricSch** [comment]
Wenn dann könnte ich im Browser/ Studio Code die Mindmap erstellen und dann eine Bilddatei ins wiki übertragen.

**Comment by Fuenfgeld** [comment]
Das würde Euch die Möglichkeit nehmen eure Grafik in versions Kontrolle zu halten. Bleibe aber eure Entscheidung

**Comment by GisstHubana** [comment]
Hinweis von Max: https://www.softwaretestinghelp.com/data-warehouse-modeling-star-schema-snowflake-schema/

- [ ] ursprungstabelle link zu unserer Tabelle = mapping-Tabelle @sajosa @JanEricSch @GisstHubana

**Comment by GisstHubana** [comment]
![image](https://user-images.githubusercontent.com/122723302/217909005-d76f791b-0021-4b39-8cec-5e363d3e6209.png)
[Link](https://data-science-blog.com/blog/2018/05/02/datenmodell-sternschema/) @sajosa @JanEricSch @GisstHubana

**Comment by JanEricSch** [comment]
abgeschlossen
