### ISSUE TITLE
Dokumentation der Quelldaten

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#6]
https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Dokumentation-der-Quelldaten

Datenbank Dokumentation:

- Erstellen sie ein Grafisches Datenbank Schema der Datenbank 

- Was sind hier Stammdaten und was sind hier Bewegungsdaten Tabellen.

> Erstellen sie eine Seite Pro Tabelle. 
> Diese Seite sollte folgende Informationen enthalten.

>> 1. SQL Create Statement
>> 2. Tabelle mit folgenden Spalten
>> 3. Spalten Bezeichnung,
>> 4. Spalten Datentyp,
>> 5. Spalten Inhaltsbeschreibung,
>> 6. Gibt es für diese Spalte ein Index? Wenn ja was ist der Index Name, was ist der Index Typ
>> 7. `Ist` diese Spalte über ein Foreign Key constraint mit einer anderen Tabelle verbunden? Wenn ja Link zu der anderen Tabellen Dokumentation.

**Comment by GisstHubana** [comment]
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell

**Comment by sajosa** [comment]
Link zur passenden WIKI Seite eingefügt

**Comment by sajosa** [comment]
**Erster Entwurf für die Visualisierung**
patient (Covid_patients, asthma_patients, metabolic_patients) [**Id**]
condition (Covid_condition, asthma_condition, metabolic_condition)[**Patient.Id** ]
medication (Covid_medication , asthma_medication , metabolic_medication ) [**Patient.Id**]
procedures (Covid_procedures  , asthma_procedures  , metabolic_medication [**Patient. Id**]
observation  (Covid_observation  , asthma_observation , metabolic_observation [**Patient. Id**]

**Comment by sajosa** [comment]
**To Do** Conditionstabelle sauber Spalte für Diagnosen / Symptome herstellen

**Comment by sajosa** [comment]
bei 80%

**Comment by JanEricSch** [comment]
Hey Sabine ich hab mal ein Graph in [Dokumentation der Quelldaten](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Dokumentation-der-Quelldaten#rehealthco-verwendete-rohdaten) eingefügt. Ist denke ich eine gute Beschreibung des ETL-Prozesses, kann vielleicht auch als Sternmodel genutzt werden. Könntest du es bitte noch besser integrieren?
@sajosa

**Comment by sajosa** [comment]
Hi @JanEricSch 
Tabellen zur Dokumentation der Quelldaten befüllt und Seite https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Dokumentation-der-Quelldaten überarbeitet.
Das Material, das noch auf andere Seiten verlagert werden muss, findet sich am Ende der Seite nach dem 

***
Rahmenstrich
***

Gutes Weiterarbeiten

**Comment by JanEricSch** [comment]
@sajosa vielen Dank!

**Comment by GisstHubana** [comment]
Observations und procedures rausgeworfen dafür encounters eingefügt

**Comment by JanEricSch** [comment]
@sajosa 
Kannst du bitte nochmal über die Datentypen in [Tabelle Patients](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Tabelle-Patients) schauen? Glaube die passen noch nicht

**Comment by sajosa** [comment]
> @sajosa Kannst du bitte nochmal über die Datentypen in [Tabelle Patients](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Tabelle-Patients) schauen? Glaube die passen noch nicht

Haben wir im Gespräch abgeschlossen heute, Danke für die Anpassungen

**Comment by sajosa** [comment]
- [x] Code Verlinkung noch einpflegen zu neuen Colab books @sajosa

**Comment by JanEricSch** [comment]
@sajosa 

habe heute nochmal die quelldaten geschaut
in den tabellen waren noch ein paar fehler beim datentyp, dass habe ich aber korrigiert
auch im er-model waren noch fehler, ich habe jetzt ein neues über mermaid erstellt
kannst gerne drüberschauen, müsste jetzt aber alles korrekt sein, wenn das für dich passt lösch doch das alte raus

damit alles einheitlich ist habe ich die bezeichnungen alle in großbuschstaben geschrieben

was du noch in den quelldaten anschauen könntest (ich weiß nicht was ich da machen soll):
* unter allen 4 tabellen gibt es noch die überschrift: 'SQL-Statements...' löschen wir die? da ist nur unter patients inhalt drunter
* in den 4 tabellen sind noch viele komplett leere spalten ('Index', 'Index Name', 'Index Typ', 'Foreign Key Constraint', Link zu verbundener Tabelle' kannst du die bitte befüllen oder löschen?

Vielen Dank

**Comment by sajosa** [comment]
@JanEricSch 

meinerseits fertig
