### ISSUE TITLE
Bitte Revision von WIKI Seite

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#65]
@GisstHubana @JanEricSch 
Liebe Beide,

bitte über folgende Seite sehen, ob alles so passt:

- [x] [d93ce0a](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/observations-(klinische-Beobachtungen)/d93ce0a1109128ae6136428cdbd4188dc2c9ba1c)

- [x] [301999d](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/patients/301999db5da08a71eca4f67a27b55a2fd2c6880a)

- [x] @GisstHubana mir fehlt noch der index Typ bei allen Tabellen bitte hier als Antwort einstellen, oder direkt in WIKI Seite einfügen :)
<del>- [ ] #66<del>

Besten Dank für Rückmeldung zu diesem Issue
Sabine

**Comment by sajosa** [comment]
- [ ] Review Fragestellung [f23a25d](https://github.com/Fuenfgeld/DMA2023TeamD/wiki/Fragestellung-und-Hypothesen/f23a25ddc79a2c08c9c9535f3f218caddda8cb67)

**Comment by GisstHubana** [comment]
Für Tabelle observations: SQL-Statements aktualisiert, Link zum G-Drive herstellt, Fremdkey Encounter gelöscht, da bei uns nicht verwendet
@sajosa: was ist ein Foreign Key constraint?
@sajosa: alle Indexe sind strings, habe es nur in der Tabelle observations aktualisiert

**Comment by GisstHubana** [comment]
@sajosa SQL-Txt File ist nun online in Github, aber ich habe null plan wie man das ins colab verlinken soll. Ich kann nur g-drive dateien verlinken
