### ISSUE TITLE
SQL-Text file im Colab book den Link im Python Skript anpassen

### ISSUE THREAD

**Issue by GisstHubana** [Fuenfgeld/DMA2023TeamD#66]

**Comment by GisstHubana** [comment]
@sajosa @JanEricSch Falls ihr wisst wie man git-hub-files über das colab ausführt, gerne ins notebook reinschreiben. Meine codeskills sind dafür zu gering

hier wäre nochmal der Link der Vorgängergruppe, die es anscheinend hinbekommen haben. Aber ich werde aus dem code nicht schlau [Link](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py)

**Comment by JanEricSch** [comment]
@sajosa @GisstHubana ist das [hier](https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/csv_data/asthma/conditions.csv) schon das pseudonym für die Daten?

**Comment by GisstHubana** [comment]
Nein 😅

**Comment by JanEricSch** [comment]
@GisstHubana löschen wir die dann wieder raus? die kann ja sonst jeder öffentlich einsehen oder?

**Comment by JanEricSch** [comment]
@GisstHubana und sollen hier überhaupt die csv Daten aus dem Warehouse geteilt werden? Oder machen wir das über einen anderen Weg?

**Comment by sajosa** [comment]
Na ich denke, wir verweisen auf synthia, oder, ich habe verstanden, wir sollen Daten und Code getrennt halten.

**Comment by JanEricSch** [comment]
@sajosa @GisstHubana andere gruppen habens geschafft die daten über google drive zu teilen, weis aber nicht wie das geht

**Comment by GisstHubana** [comment]
@JanEricSch @sajosa ich habe gestern noch die verwendeten Ursprungs-csv-Dateien in den Ordner https://github.com/Fuenfgeld/DMA2023TeamD/tree/main/csv_data geladen, da unsere Daten ja synthetisiert sind und somit veröffentlichbar sind. Ganz korrekt wäre die Ursprungstabellen zu anonymisieren, die anonymisierten csv-Dateien zu veröffentlichen und dann den ETL-Prozess drüber laufen zu lassen. 
@sajosa was denkst du? Sollen wir den ganz korrekten Weg gehen? Dann hätten wir auch nicht das Problem dass wir nun eine Tabelle mir ca. 50 Spalten anonymisieren müssen. Aber wir müssten dann 3x 4 Tabellen anonymisieren. Ich würde das Umschreiben morgen codetechnisch noch hinbekommen.

**Comment by GisstHubana** [comment]
> Na ich denke, wir verweisen auf synthia, oder, ich habe verstanden, wir sollen Daten und Code getrennt halten.

@sajosa @JanEricSch Ich habe verstanden wir sollen das in getrennte Ordner packen. Daher gibst nun den neuen order:
https://github.com/Fuenfgeld/DMA2023TeamD/tree/main/csv_data

> @sajosa @GisstHubana andere gruppen habens geschafft die daten über google drive zu teilen, weis aber nicht wie das geht

wir können auch über google teilen, hätten dann aber das Problem, dass wir den Ordner unbegrenzt für alle freigeben müssten. Ansonsten hat max ja auch noch in den akutellen video auf die archivierung verwiesen, das könnten wir auch nutzen... ich wäre für die github-Lösung. Google ginge auch, dann schreib ich den code zurück um. Archivierung müsste ich mich erst einlesen...

**Comment by JanEricSch** [comment]
@GisstHubana da würde ich lieber gar keine csv Daten hochladen und schreiben, dass man nur über uns an die dran kommt

**Comment by GisstHubana** [comment]
SQL-Text und Python-Code angepasst auf Github und g-Drive
