### ISSUE TITLE
Zusammenfassung der Quelldaten in eigener Datenbank - Rohdatenbank2.0.ipynb

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#7]
Erstellen sie ein GoogleColabbook mit der Übungsdatei  
**Link zum Colabbook:** https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/1_Rohdatenbank.ipynb
**Link zur Textdatei mit SQL Statements:**

(Empfohlen: Verbinden sie das Colabbook mit ihrem git Repositorium und checken sie dort die Änderungen regelmäßig ein)

> 1. Importieren sie Alle CSV Dateien in eine CSV Datenbank.
> 2. Erstellen sie dafür SQL Create Statements
> 3. Erstellen sie Indexe auf die Spalten die häufig zum Suchen benutzt wird.
> 4. Erstellen sie Foreign Key constraints um die CSV Dateien miteinander zu verbinden

(es wird empfohlen die SQL Statements in einem separaten Text File anzulegen und dann in das Colabbook zu importieren)

**Comment by sajosa** [comment]
Finale Zusammenstellung

**Comment by GisstHubana** [comment]
<del>Erstellen sie ein GoogleColabbook.
(Empfohlen: Verbinden sie das Colabbook mit ihrem git Repositorium und checken sie dort die Änderungen regelmäßig ein)
Importieren sie Alle CSV Dateien in eine CSV Datenbank.
Erstellen sie dafür SQL Create Statements
Erstellen sie Indexe auf die Spalten die häufig zum Suchen benutzt wird.
Erstellen sie Foreign Key constraints um die CSV Dateien miteinander zu verbinden
(es wird empfohlen die SQL Statements in einem separaten Text File anzulegen und dann in das Colabbook zu importieren)<del>

Datenbank Dokumentation:
Erstellen sie ein Grafisches Datenbank Schema der Datenbank
Was sind hier Stammdaten und was sind hier Bewegungsdaten Tabellen.
Erstellen sie eine Seite Pro Tabelle. Diese Seite sollte folgende Informationen enthalten.
SQL Create Statement
Tabelle mit folgenden Spalten
Spalten Bezeichnung,
Spalten Datentyp,
Spalten Inhaltsbeschreibung,
Gibt es für diese Spalte ein Index? Wenn ja was ist der Index Name, was ist der Index Typ
Ist diese Spalte über ein Foreign Key constraint mit einer anderen Tabelle verbunden? Wenn ja Link zu der anderen Tabellen Dokumentation.

**Comment by sajosa** [comment]
<del>DB COVID @GisstHubana 
Asthma @sajosa 
Metabolic @JanEricSch <del>

**Comment by sajosa** [comment]
Hier der Link zur neuen Datei
https://github.com/Fuenfgeld/DMA2023TeamD/blob/main/Rohdatenbank2_0.ipynb

**Comment by sajosa** [comment]
<del>Dieser Code scheint nicht zu funktionieren

<del>cur.execute("CREATE INDEX idx_patients_name ON patients (FIRST, LAST)")
cur.fetchall()

<del>cur.execute("CREATE INDEX idx_patients_name ON patients (FIRST, LAST)")
cur.fetchall() <del>

Funktioniert

**Comment by GisstHubana** [comment]
Datendank COVID19 enthält Tabellen: patients, medications, procedures, observations, conditions
Datendank Asthma enthält Tabellen: patients, medications, procedures, observations, conditions
Datendank metabolic_syndrome_disease enthält Tabellen: patients, medications, procedures, observations, conditions

Index: 
COVID19: patients - FIRST, LAST; medications - PATIENT; procedures - PATIENT; observations - PATIENT; conditions - PATIENT
Asthma: patients - FIRST, LAST; medications - PATIENT; procedures - PATIENT; observations - PATIENT; conditions - PATIENT
metabolic_syndrome_disease: patients - FIRST, LAST; medications - PATIENT; procedures - PATIENT; observations - PATIENT; conditions - PATIENT 

@sajosa Hinweis für Datenbankmodell

**Comment by GisstHubana** [comment]
Einziges Problem: alle Tabelle heißen gleich, sie liegen nur in anderen Ordnern (COVID19/Asthma/metabolic_syndrome_disease), sonst hätte ich die CSV-Dateien nicht einlesen können. 

Unsere Datenbank ist somit fertig. Beim merge sollten wir daran denken, dass die Tabellen gleich heissen und sie ggf. vorher umbenennen

Seid ihr einverstanden, das Issue Erstellung Datenbank zu schließen?

**Comment by sajosa** [comment]
Super, erstmal herzlichen Dank 
![приветGIF](https://user-images.githubusercontent.com/122606103/213900043-75fc16e3-27d8-4791-995b-7882a08490b0.gif)

**Comment by sajosa** [comment]
@GisstHubana 
Folgendes habe ich noch nicht ganz verstanden
""Beim merge sollten wir daran denken, dass die Tabellen gleich heissen und sie ggf. vorher umbenennen""
Frage:
Bei welchem merge?
Bei zukünftigen?
Oder in general?


Besten Dank für Klarifizierung :)

**Comment by sajosa** [comment]
@GisstHubana 
"Seid ihr einverstanden, das Issue Erstellung Datenbank zu schließen?"
Dieses Issue würde ich erst schließen, wenn wir die abschließende Freigabe von Max haben.

Sind wir denn soweit, dass wir sein review anfragen können?
@JanEricSch @GisstHubana

**Comment by GisstHubana** [comment]
https://github.com/Fuenfgeld/DMA2023TeamD/issues/7#issuecomment-1399399295
@sajosa Genau beim Zukünftigen Merge.
Ich glaube wir brauchen noch das Datenbankschema bevor wir das Review anfragen können oder?

**Comment by GisstHubana** [comment]
Übrigens hier noch die Namen der Indexe (ich habe mich bei der Namensgebung an der Hausaufgabe orientiert, daher die seltsamen Namen) @sajosa für das Datenbankschema:

COVID19: patients - FIRST, LAST - Indexname (für beide Spalten) "idx_contacts_name" ; medications - PATIENT -  Indexname "idx_patname_medications"; procedures - PATIENT - Indexname "idx_patname_procedures"; observations - PATIENT - Indexname "idx_patname_observations"; conditions - PATIENT - Indexname "idx_patname_conditions"

Asthma: patients - FIRST, LAST - Indexname (für beide Spalten) "idx_contacts_asthma_name" ; medications - PATIENT -  Indexname "idx_patname_asthma_medications"; procedures - PATIENT - Indexname "idx_patname_asthma_procedures"; observations - PATIENT - Indexname "idx_patname_asthma_observations"; conditions - PATIENT - Indexname "idx_patname_asthma_conditions"

metabolic_syndrome_disease: patients - FIRST, LAST - Indexname (für beide Spalten) "idx_contacts_metabolic_name" ; medications - PATIENT -  Indexname "idx_patname_metabolic_medications"; procedures - PATIENT - Indexname "idx_patname_metabolic_procedures"; observations - PATIENT - Indexname "idx_patname_metabolic_observations"; conditions - PATIENT - Indexname "idx_patname_metabolic_conditions"

**Comment by sajosa** [comment]
> [#7 (comment)](https://github.com/Fuenfgeld/DMA2023TeamD/issues/7#issuecomment-1399399295) @sajosa Genau beim Zukünftigen Merge. Ich glaube wir brauchen noch das Datenbankschema bevor wir das Review anfragen können oder?

Ok, das sollte der neue Workflow für die Dateienabwicklung insbesondere nach Anlegen einer FORK für die Zukunft vermeiden können.

**Comment by GisstHubana** [comment]
Komplett abgeschlossen vgl. meine letzten Post unter #42
