### ISSUE TITLE
Datenschutz Folgeabschätzung

### ISSUE THREAD

**Issue by GisstHubana** [Fuenfgeld/DMA2023TeamD#72]
https://github.com/Fuenfgeld/DatamanagementAndArchiving/wiki/Template-Datenschutz-Folgenabsch%C3%A4tzung

**Comment by GisstHubana** [comment]
Dran denken: [Anonymisierung von Patientendaten](https://www.youtube.com/watch?v=SihYp9YuCc8)

**Comment by sajosa** [comment]
@GisstHubana @JanEricSch 
Vorschlag:
Mögliches Konzept zum Schutz der Patientendaten wäre meiner Meinung nach Folgendes:
Wir haben die Möglichkeit, sensible Daten im Schritt von Rohdatenbank zu Datawarehouse gar nicht erst mit zu nehmen, d.h. Spalten raus zu lassen, den Pat eine unabhängige Nr  zuzuordnen --> (ggf. Mappingtabelle? für Patientenid und Neue Pat.nr. in unserem Bestand halten)

**Comment by sajosa** [comment]
erledigt
