### ISSUE TITLE
Gruppenmeeting KW6 (05.02.2023- 12.02.2023)

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#73]
@GisstHubana @JanEricSch @sajosa 

ToDos aus Onlinemeeting mit Max
- [x] Datenchutzfolgeabschätzung (Patientenids--> Pseudonymisieren) (#72)
- [x] wie wird der Code reproduzierbar? (#70)
- [x] - Systemumgebung für den Code dokumentieren
- [x] In Tests umwandeln was wie schon als Test geschrieben haben
- [x] Testkriterien definieren 
- für Test muss definiert werden wann ein Test bestanden wird und wann er nicht bestanden ist.
- das kann man automatisieren, Plausibilitätsprüfungen

Präsentation (in Arbeit siehe #44 )
- Ziel für Präsentation: es soll einfach verständlich sein
- einerseits Was haben wir gemacht in einer verständlichen Präsentation (Erklärung des Kontext, Forschungsfragen, **technische Sachen erklären!!!!** Ergebnisse erläutern
- Fokus auf das wo wir stolz drauf sind.
- nicht alles abdecken, eine Sache, auf die wir besonders stolz sind.
-

**Comment by GisstHubana** [comment]
Für beide Themen hab ich schon eigene Issues erstellt #72 #70 
Um #70 kümmere ich mich gerne, da hat Max schon eine gute Hilfestellung im Video gegeben
Bei #72 bau ich gerne mit. Vielleicht können wir die Wiki-Seite von Max clonen und dann an uns anpassen? @sajosa @JanEricSch

**Comment by GisstHubana** [comment]
Wann wollt ihr gerne das Video drehen? Ich hab ab Sonntag, 12.02., 1 Woche Urlaub. Heißt ich kann viel machen und bin zeitlich flexibel :) Vor Weiberfasching (ich glaub das ist was bayerisches, oder? Das wäre Do, 16.02.) wäre der Hammer :D aber danach ist natürlich auch in Ordnung ;) @sajosa @JanEricSch

**Comment by sajosa** [comment]
**Verlinken** des Codes zur  Dokumentation
Comit verifzier zu den Versionen der benutzten  (requierements datei für Python)
--> Video von dieser Woche
Dimensionstabellen?

**Comment by sajosa** [comment]
Quellen von Max:
von Maximilian Fünfgeld an alle:    7:43 PM
https://github.com/Fuenfgeld/GitHubDemo/blob/main/Untitled0.ipynb
von Maximilian Fünfgeld an alle:    8:01 PM
https://github.com/Fuenfgeld/DatamanagementAndArchiving/wiki/Template-Datenschutz-Folgenabsch%C3%A4tzung
von Maximilian Fünfgeld an alle:    8:23 PM

Video zu Anonymisierung:
https://youtu.be/SihYp9YuCc8

**Comment by sajosa** [comment]
Im Datenmanagmentplan verlinkungen zu den Subseiten
In readme Verlinkung zum WIKI !!!

**Comment by sajosa** [comment]
HInweis für Code 
Trennen, Sachen auslagern, eventuell ein ETL-Notbook machen

**Comment by GisstHubana** [comment]
#74 test als print-Funktion, z.B. im ETL-Prozess [Codelink](https://colab.research.google.com/github/Fuenfgeld/DMA2023TeamD/blob/main/Code/ReHealthCo_ETL.ipynb#scrollTo=y84zrYRs3Gjx&line=1&uniqifier=1)
