### ISSUE TITLE
Datenmaterial in Driveordner hochladen

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#9]
csv für Kosten @JanEricSch 

sql in Jupiter einbinden @GisstHubana

**Comment by sajosa** [comment]
Hier nochmal der Link zur Doko der Daten: https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary

**Comment by GisstHubana** [comment]
https://drive.google.com/drive/folders/0AEzNFkh5sBp0Uk9PVA

Erledigt :)
